metadata:
    id: christoph-borg
    language: swe

import:
    importer: text_import:parse

export:
    annotations:
        - <sentence>
        - <token>
        - <token:word>
        - <token>:stanza.pos
        - swener.ne:swener.ex
        - swener.ne:swener.type
        - swener.ne:swener.subtype
        - swener.ne:swener.name
        - sbx_ocr_correction_viklofg_sweocr.ocr_correction
        - sbx_ocr_correction_viklofg_sweocr.ocr_correction:sbx_ocr_correction_viklofg_sweocr.ocr-correction--viklofg-sweocr
        
sparv:
    compression: none
